### PR TITLE
Specify an operating system

### PR DESCRIPTION
**Pull request by TigerND**

### CODE REVIEW

**Comment by fritx** [comment]
So I have to move it into `optionalDependency` in a cross-platform app?

**Comment by coreybutler** [comment]
@fritx - Not sure what you're trying to do... this is specific to OSX.

**Comment by fritx** [comment]
@coreybutler yeah.. but I was building a cross-platform app where I wanted to include `node-mac` togehter to be required once on OSX, but it would break the whole `npm install`

**Comment by TigerND** [comment]
https://gist.github.com/TigerND/ce022338c9f0c0a38d9c
https://gist.github.com/TigerND/158f778995598c1859e7

**Comment by coreybutler** [comment]
I tend to just write a preinstall script (i.e. package.json) to detect the OS and install accordingly. Also, the node-* series really isn't designed for use with systems like nwjs or Electron. Both of those environments have their own native process managers.

**Comment by fritx** [comment]
Thanks for these two tips! Great

**Pull request merged**
