### PR TITLE
Allow run as user previlege

### LINKED ISSUE #29: Run as normal user privilege
Currently, it is run as root privilege, this cause following problem when I use `node-mac` to run git related script:

Git commit show as System Adminstrator
Screen Shot 2020-05-06 at 1 07 27 PM

Can't commit by hand because lack of privilege, I have to reset privilege every time:
`sudo chown -R $(whoami) /xxx/repo`

Can't push: https://github.com/simonthum/git-sync/issues/17

SO how to run a task as normal user privilege?

### PR DESCRIPTION
**Pull request by linonetwo**
A new config `config.runAsUser` for this.

Resolves #29

### CODE REVIEW

**Comment by linonetwo** [comment]
This PR completely removes the requirement for the `sudo`.

And it will work in many usecase.

**Comment by linonetwo** [comment]
For people can't wait for this PR to be merged, I've released a `node-mac-user` package for my self.

**Comment by coreybutler** [comment]
@linonetwo - I'll merge this, but there need to be a few minor changes. First, please rebase your PR to sync up with the recent changes in 1.0.0 (there have been several updates). Second, please remove the template literals in favor of the older syntax. While they're super handy, there are a number of users who use this library with significantly older versions of Node, which do not support template literals. After that, I'd be happy to merge this.

**Comment by linonetwo** [comment]
Edited as requested, test the example still work, when adding:

```
svc = new Service({ 
      logOnAsUser: true, 
```

and log in `/Users/linonetwo/Library/Logs/Hello World` shows no error, and http://127.0.0.1:3000/ has output.

**Comment by coreybutler** [comment]
LGTM - I'll run a final check tonight and should be able to publish this in 1.0.1. Thanks for the contribution!!

**Comment by coreybutler** [comment]
1.0.1 has been released.

**Comment by arturo-mendivil** [comment]
would be good to add all available options that a serviceConfig can have in the README, or writing a types file to infer easily all options that can be passed to a service

**Pull request merged**
